### ISSUE TITLE
GetInitialProps on child routes / components 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [rayandrews/centarius#8]
Looking through your source, I see some promising things. 

Is there any chance you’ve solved for async data fetching on nested routes or child components? 

Big flaw with all SSR solutions is nested routing and SSR don’t work together. Like with next js or even my own projects like redux first router

**Comment by natanelia** [comment]
@ScriptedAlchemy Yes, this is what centarius is designed for. In Dekoruma, we use centralized nested route config with Razzle SSR and it is being run in production.

**Comment by ScriptedAlchemy** [comment]
Wow! Congratulations on cracking this! It’s been a major challenge for me on my latest router. 

So I’m trying to understand one other thing here. You speak of razzle, is this project a router? Or a server? 

If you’re running razzle, then you’ve got some other infrastructure acting as the server. Could this project replace next.js routing system, or is it itself a full replacement of something like next.js? Just trying to fully understand. 

I’m a big fan of Centralized router configs. One painful issue is discovering side effects as you traverse the tree. Having a defined schema upfront effectively solves for unpredictability and establishes a controller like pattern. You’ve also added router life cycles which is fantastic to see. Something always missing from react architecture

**Comment by davidkwan95** [comment]
@ScriptedAlchemy This project is a modification of [After.js](https://github.com/jaredpalmer/after.js) to enable nested routes.

After.js itself is inspired by next.js, but the author is not fond of next.js routing system. Quoting from after.js description:

> Next.js-like framework for server-rendered React apps built with React Router 4
